echo "Go to boruvka.felk.cvut.cz or zorn.felk.cvut.cz"
echo "Set and export the INLOC_EXPERIMENT_NAME environment variable"
echo "Go to a repository that contains the source code of the experiment"
echo "Execute run_cmp_gpu.sh"
echo "Wait for the program to finish successfully"
echo "Go to cmpgrid-65 or cmpgrid-69 or cmpgrid-71 (from ptak.felk.cvut.cz)"
echo "Set and export the INLOC_EXPERIMENT_NAME environment variable"
echo "Go to a repository that contains the source code of the experiment"
echo "Execute run_cmp_cpu.bash"